### ISSUE TITLE
EC2 - only the first reservation returned from ec2 describe intstances is processed

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-import-aws-account-scraper#2]
### What happened?

In the ec2 describe instances call, only the first reservation is processed while reservation can be 0-n.

### Expected Behavior

scraper should import all ec2 instances, not just the first set of reservations.

### Steps to reproduce

Use an AWS account with more than 1 set of ec2 reservations

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkodroff** [comment]
Fixed by #3. (Forgot to close earlier.)
